version: "3.9"
services: 
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: RoomSchedulerAPI
    depends_on: 
      - db
    ports:
      - 31414:80
    volumes:
      - ./api:/home/app

  db:
    image: mysql
    container_name: RoomSchedulerDB
    environment:
      MYSQL_ROOT_PASSWORD: dubbsdibbets
      MYSQL_DATABASE: RoomScheduler
    ports:
      - 31415:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d

